version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.22
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Run tests
          command: go test ./...

      - run:
          name: Build binary
          command: go build -o bin/invoicer .

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
              IMAGE_TAG=${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME}:latest
              docker build -t $IMAGE_TAG .
              docker push $IMAGE_TAG
            fi
