version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.22
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Run tests
          command: go test ./...

      - run:
          name: Build binary
          command: go build -o bin/invoicer .

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
              IMAGE_NAME=dmitriydikt/invoicer-chapter2
              IMAGE_TAG=${CIRCLE_SHA1:0:7}   # первые 7 символов коммита
              docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$IMAGE_TAG .
              docker push $IMAGE_NAME:latest
              docker push $IMAGE_NAME:$IMAGE_TAG
            fi
